In [12]:
import pandas as pd
import re
%matplotlib inline

# Get the raw data.
seeds = pd.read_csv("results-20160708-200613.txt")

# Extract the seeds.
def match_with_nones(s):
    try:
        return re.search("=\d*", str(s)).group(0)[1:]
    except AttributeError:
        return None
seeds['Seed'] = seeds['extract'].map(match_with_nones)

# Reformat to index by seed.
seeds = seeds.groupby('Seed').sum().rename(columns={'f0_': 'Count'})
# Remove the empty option.
seeds.drop("", inplace=True)
# Add a percent column.
seeds['Percent'] = seeds['Count'] / seeds['Count'].sum()
# Sort
seeds = seeds.sort_values(by='Count', ascending=False)
seeds.to_csv("seeds.csv")

In [14]:
seeds

                      Count   Percent
Seed
0                      3845  0.400146
42                     1661  0.172859
1                      1614  0.167968
1234                    398  0.041420
123                     168  0.017484
10                      136  0.014153
3                       120  0.012488
12345                   105  0.010927
2                        99  0.010303
5                        67  0.006973
100                      59  0.006140
4                        39  0.004059
13                       38  0.003955
11                       36  0.003746
1999                     35  0.003642
113                      33  0.003434
8                        32  0.003330
23                       29  0.003018
211                      28  0.002914
9                        26  0.002706
234                      25  0.002602
12                       24  0.002498
123456                   24  0.002498
1337                     23  0.002394
1234567                  23  0.002394
15                       23  0.002394
666                      20  0.002081
12345678901              18  0.001873
17                       18  0.001873
7                        18  0.001873
...                     ...       ...
4562                      1  0.000104
4567                      1  0.000104
458127641                 1  0.000104
47                        1  0.000104
1500                      1  0.000104
4747                      1  0.000104
243                       1  0.000104
4905                      1  0.000104
14695981039346656037      1  0.000104
4338                      1  0.000104
43212                     1  0.000104
1701                      1  0.000104
41                        1  0.000104
3849058430                1  0.000104
3886                      1  0.000104
392                       1  0.000104
1960                      1  0.000104
1956                      1  0.000104
19                        1  0.000104
4096                      1  0.000104
413                       1  0.000104
432                       1  0.000104
419884521                 1  0.000104
1796                      1  0.000104
179                       1  0.000104
177774                    1  0.000104
42424242                  1  0.000104
1729                      1  0.000104
43143                     1  0.000104
28                        1  0.000104

[326 rows x 2 columns]